### ISSUE TITLE
extraction of filename VS valid class names

### ISSUE THREAD

**Issue by bdurrer** [undercloud/gulp-svg-inline-css#1]
I got some svg from our designer and it turns out that she likes spaces in filenames... which of course results in invalid class names

`Bookingcentre big color.svg` becomes `.Bookingcentre big color { ... }`, ooops :)

I would say file names should be normalized (e.g. [A-Za-z0-9]). Or even better, a callback to customize the class name of every single svg.

**Comment by undercloud** [comment]
Done, enjoy! https://github.com/undercloud/gulp-svg-inline-css#class-names
